#!/usr/bin/env python3
"""
Heightmap to 3D Mesh Converter

Converts grayscale heightmap images to 3D mesh files (OBJ, STL, PLY)
suitable for import into Blender, 3D printing, or game engines.

Usage:
    python heightmap_to_mesh.py heightmap.png -o terrain.obj
    python heightmap_to_mesh.py heightmap.png -o terrain.stl --scale 1,1,0.5
    python heightmap_to_mesh.py heightmap.png -o terrain.obj --decimate 4
"""

import argparse
import os
import numpy as np
from PIL import Image


def load_heightmap(path):
    """
    Load heightmap image and normalize to 0-1 range.

    Supports 8-bit and 16-bit grayscale images.
    """
    img = Image.open(path)

    # Convert to grayscale if needed
    if img.mode != 'L' and img.mode != 'I;16':
        img = img.convert('L')

    data = np.array(img, dtype=np.float32)

    # Normalize based on bit depth
    if img.mode == 'I;16' or data.max() > 255:
        data = data / 65535.0
    else:
        data = data / 255.0

    return data


def create_mesh(heightmap, scale=(1.0, 1.0, 1.0), decimate=1):
    """
    Create 3D mesh vertices and faces from heightmap.

    Args:
        heightmap: 2D numpy array of height values (0-1)
        scale: (x, y, z) scale factors
        decimate: Decimation factor (1 = full res, 2 = half, etc.)

    Returns:
        vertices: Nx3 array of vertex positions
        faces: Mx3 array of triangle indices
    """
    # Flip Y-axis: image Y=0 is top, but 3D Y=0 is bottom
    # This makes image top → mesh north (positive Y)
    heightmap = np.flipud(heightmap)

    # Decimate if requested
    if decimate > 1:
        heightmap = heightmap[::decimate, ::decimate]

    h, w = heightmap.shape
    scale_x, scale_y, scale_z = scale

    # Create vertex grid
    # X and Y are normalized to [-0.5, 0.5] range, then scaled
    x = np.linspace(-0.5, 0.5, w) * scale_x
    y = np.linspace(-0.5, 0.5, h) * scale_y
    xx, yy = np.meshgrid(x, y)

    # Z is height value scaled
    zz = heightmap * scale_z

    # Flatten to vertex list
    vertices = np.stack([xx.ravel(), yy.ravel(), zz.ravel()], axis=1)

    # Create triangle faces
    # Each quad (4 vertices) becomes 2 triangles
    faces = []
    for row in range(h - 1):
        for col in range(w - 1):
            # Vertex indices for this quad
            v0 = row * w + col
            v1 = row * w + col + 1
            v2 = (row + 1) * w + col
            v3 = (row + 1) * w + col + 1

            # Two triangles per quad
            faces.append([v0, v2, v1])
            faces.append([v1, v2, v3])

    faces = np.array(faces, dtype=np.int32)

    return vertices, faces


def compute_normals(vertices, faces):
    """Compute per-vertex normals by averaging face normals."""
    normals = np.zeros_like(vertices)

    for face in faces:
        v0, v1, v2 = vertices[face]
        edge1 = v1 - v0
        edge2 = v2 - v0
        face_normal = np.cross(edge1, edge2)
        norm = np.linalg.norm(face_normal)
        if norm > 0:
            face_normal /= norm
        for idx in face:
            normals[idx] += face_normal

    # Normalize
    norms = np.linalg.norm(normals, axis=1, keepdims=True)
    norms[norms == 0] = 1
    normals /= norms

    return normals


def save_obj(path, vertices, faces, normals=None):
    """Save mesh in Wavefront OBJ format."""
    with open(path, 'w') as f:
        f.write("# Heightmap mesh generated by heightmap_to_mesh.py\n")
        f.write(f"# Vertices: {len(vertices)}, Faces: {len(faces)}\n\n")

        # Write vertices
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")

        # Write normals if provided
        if normals is not None:
            f.write("\n")
            for n in normals:
                f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")

        # Write faces (OBJ uses 1-based indexing)
        f.write("\n")
        if normals is not None:
            for face in faces:
                f.write(f"f {face[0]+1}//{face[0]+1} {face[1]+1}//{face[1]+1} {face[2]+1}//{face[2]+1}\n")
        else:
            for face in faces:
                f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")


def save_stl(path, vertices, faces, binary=True):
    """Save mesh in STL format."""
    if binary:
        save_stl_binary(path, vertices, faces)
    else:
        save_stl_ascii(path, vertices, faces)


def save_stl_ascii(path, vertices, faces):
    """Save mesh in ASCII STL format."""
    with open(path, 'w') as f:
        f.write("solid heightmap\n")

        for face in faces:
            v0, v1, v2 = vertices[face]
            edge1 = v1 - v0
            edge2 = v2 - v0
            normal = np.cross(edge1, edge2)
            norm = np.linalg.norm(normal)
            if norm > 0:
                normal /= norm

            f.write(f"  facet normal {normal[0]:.6f} {normal[1]:.6f} {normal[2]:.6f}\n")
            f.write("    outer loop\n")
            f.write(f"      vertex {v0[0]:.6f} {v0[1]:.6f} {v0[2]:.6f}\n")
            f.write(f"      vertex {v1[0]:.6f} {v1[1]:.6f} {v1[2]:.6f}\n")
            f.write(f"      vertex {v2[0]:.6f} {v2[1]:.6f} {v2[2]:.6f}\n")
            f.write("    endloop\n")
            f.write("  endfacet\n")

        f.write("endsolid heightmap\n")


def save_stl_binary(path, vertices, faces):
    """Save mesh in binary STL format (smaller file size)."""
    import struct

    with open(path, 'wb') as f:
        # 80-byte header
        header = b'Binary STL from heightmap_to_mesh.py' + b'\0' * 43
        f.write(header[:80])

        # Number of triangles
        f.write(struct.pack('<I', len(faces)))

        # Write triangles
        for face in faces:
            v0, v1, v2 = vertices[face]
            edge1 = v1 - v0
            edge2 = v2 - v0
            normal = np.cross(edge1, edge2)
            norm = np.linalg.norm(normal)
            if norm > 0:
                normal /= norm

            # Normal
            f.write(struct.pack('<3f', *normal))
            # Vertices
            f.write(struct.pack('<3f', *v0))
            f.write(struct.pack('<3f', *v1))
            f.write(struct.pack('<3f', *v2))
            # Attribute byte count
            f.write(struct.pack('<H', 0))


def save_ply(path, vertices, faces, normals=None):
    """Save mesh in PLY format."""
    with open(path, 'w') as f:
        f.write("ply\n")
        f.write("format ascii 1.0\n")
        f.write(f"element vertex {len(vertices)}\n")
        f.write("property float x\n")
        f.write("property float y\n")
        f.write("property float z\n")
        if normals is not None:
            f.write("property float nx\n")
            f.write("property float ny\n")
            f.write("property float nz\n")
        f.write(f"element face {len(faces)}\n")
        f.write("property list uchar int vertex_indices\n")
        f.write("end_header\n")

        # Write vertices
        if normals is not None:
            for v, n in zip(vertices, normals):
                f.write(f"{v[0]:.6f} {v[1]:.6f} {v[2]:.6f} {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
        else:
            for v in vertices:
                f.write(f"{v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")

        # Write faces
        for face in faces:
            f.write(f"3 {face[0]} {face[1]} {face[2]}\n")


def main():
    parser = argparse.ArgumentParser(
        description='Convert heightmap image to 3D mesh for Blender',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    %(prog)s heightmap.png -o terrain.obj
    %(prog)s heightmap.png -o terrain.stl --scale 100,100,10
    %(prog)s heightmap.png -o terrain.obj --decimate 4 --no-normals

Scale:
    --scale X,Y,Z where:
    - X: width of the mesh
    - Y: depth of the mesh
    - Z: height multiplier (elevation exaggeration)

Decimate:
    Reduces mesh resolution by factor N. Use for large heightmaps:
    - 1: Full resolution (default)
    - 2: Half resolution (1/4 triangles)
    - 4: Quarter resolution (1/16 triangles)

Output formats:
    .obj - Wavefront OBJ (recommended for Blender)
    .stl - STL (good for 3D printing)
    .ply - PLY (supports normals)
        """
    )
    parser.add_argument('input', help='Input heightmap image (PNG)')
    parser.add_argument('--output', '-o', required=True,
                        help='Output mesh file (.obj, .stl, or .ply)')
    parser.add_argument('--scale', '-s', type=str, default='1,1,1',
                        help='Scale as X,Y,Z (default: 1,1,1)')
    parser.add_argument('--decimate', '-d', type=int, default=1,
                        help='Decimation factor (default: 1, no decimation)')
    parser.add_argument('--no-normals', action='store_true',
                        help='Skip normal calculation (faster)')
    parser.add_argument('--ascii-stl', action='store_true',
                        help='Use ASCII format for STL (larger but readable)')

    args = parser.parse_args()

    # Parse scale
    scale = tuple(float(x) for x in args.scale.split(','))
    if len(scale) != 3:
        print("Error: Scale must be X,Y,Z (e.g., 100,100,10)")
        return 1

    # Determine output format
    ext = os.path.splitext(args.output)[1].lower()
    if ext not in ['.obj', '.stl', '.ply']:
        print(f"Error: Unsupported format '{ext}'. Use .obj, .stl, or .ply")
        return 1

    # Load heightmap
    print(f"Loading heightmap: {args.input}")
    heightmap = load_heightmap(args.input)
    print(f"  Size: {heightmap.shape[1]} x {heightmap.shape[0]}")
    print(f"  Height range: {heightmap.min():.3f} - {heightmap.max():.3f}")

    # Create mesh
    print(f"Creating mesh (scale={scale}, decimate={args.decimate})...")
    vertices, faces = create_mesh(heightmap, scale=scale, decimate=args.decimate)
    print(f"  Vertices: {len(vertices):,}")
    print(f"  Triangles: {len(faces):,}")

    # Compute normals if needed
    normals = None
    if not args.no_normals and ext != '.stl':
        print("Computing normals...")
        normals = compute_normals(vertices, faces)

    # Save mesh
    print(f"Saving: {args.output}")
    os.makedirs(os.path.dirname(args.output) or '.', exist_ok=True)

    if ext == '.obj':
        save_obj(args.output, vertices, faces, normals)
    elif ext == '.stl':
        save_stl(args.output, vertices, faces, binary=not args.ascii_stl)
    elif ext == '.ply':
        save_ply(args.output, vertices, faces, normals)

    # File size
    size_mb = os.path.getsize(args.output) / (1024 * 1024)
    print(f"  File size: {size_mb:.1f} MB")
    print("Done!")

    return 0


if __name__ == '__main__':
    exit(main())
